name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Notify build success to slack
        uses: rtCamp/action-slack-notify@v2
        if: success()
        env:
          SLACK_CHANNEL: notifications
          SLACK_COLOR: '#36a64f'
          SLACK_ICON: https://my-oqe2422.slack.com/services/B01PGDYATUY?settings=1
          SLACK_USERNAME: SLACK_USERNAME2
          SLACK_TITLE: SLACK_TITLE3
          SLACK_MESSAGE: SLACK_MESSAGE4
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
