name: CI

on: [push]

env:
  CI: true
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}


      - name: Slack notification FAILED
        uses: Ilshidur/action-slack@2.1.0
        if: failure()
        env:
          SLACK_AVATAR: sender # optional: repository, sender or ImageURL
          SLACK_CHANNEL: '#notifications'
        with:
          args: "Lint checks *FAILED* for {{GITHUB_REPOSITORY}}*\nYo {{GITHUB_ACTOR}} see why at <{{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/commit/{{GITHUB_SHA}}/checks|action logs>"

      - name: Slack notification SUCCESS
        uses: Ilshidur/action-slack@2.1.0
        if: success()
        with:
          args: "Lint checks *SUCCESSFUL!*\nfrom {{ GITHUB_ACTOR }} at {{ GITHUB_REPOSITORY }}"
