name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          CI: true
      - name: Notify build success to slack
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.ACCESS_TOKEN }}
          SLACK_USERNAME: 'gardner'
          SLACK_CHANNEL: '#notifications'
          SLACK_AVATAR: repository
          SLACK_COLOR: success
        uses: Ilshidur/action-slack@2.0.2
      - name: Notify build failure to slack
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.ACCESS_TOKEN }}
          SLACK_USERNAME: 'gardner'
          SLACK_CHANNEL: '#notifications'
          SLACK_AVATAR: repository
          SLACK_COLOR: fail
        uses: Ilshidur/action-slack@2.0.2
