name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          CI: true
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.ACCESS_TOKEN }}
          SLACK_USERNAME: ThisIsMyUsername # Optional. (defaults to webhook app)
          SLACK_CHANNEL: general # Optional. (defaults to webhook)
          SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
        uses: Ilshidur/action-slack@2.0.2
